### ISSUE TITLE
Roadmap / todos

### ISSUE THREAD

**Issue by vadimnazarov** [imminfo/tcr#1]
## Code

**2.2.2 version**
- [x] Fix a bug in `geneUsage` with cbind-rbind on joint genes.
- [x] Fix a bug with .text in `pca.segments.2D`.
- [x] `bunch.translate` and `revcomp` as an input could receive small letters 
- [ ] Add the `trackClonotypes` function for tracking a number of sub repertoires through a list of repertoires.
- [ ] Refactor `get.kmers` - simple input, ID for columns.
- [ ] Optimise `get.kmers` using C++.
- [ ] Optimise `intersectClonesets` when apply to lists (C++).
- [ ] Optimise `find.similar.sequences` when apply to lists (of patterns) (C++).
  - [ ] Write an optimised hamming / edit distance sequences search procedure.
    - [ ] BLAST-like heuristics / kmer index.
      - [ ] problem: very big edit distance.
- [x] Add the `downsample` function.
- [x] Rename `get.n.barcodes` to `resample` for consistency.
- [ ] Fix issue in `parse.mixcr` with alignments if no alignment in the input file.
- [ ] Fix `parse.immunoseq` - remove `parse.immunoseq2` and add `count (templates)` as UMIs.
- [ ] Add columns for V-, D- and J-genes subgroups and genes OR transform geneUsage function so it could infer genes/subgroups from the allele data.
- [ ] Add a bootstrap CI to `rarefaction`.
- [x] Add permutation tests.
- [ ] Add `hill.numers` and `vis.hill.numbers`.
- [ ] Add the `simplePCA` function - a wrapper for different PCA methods.
- [ ] Store segments in text tables, not in vectors
- [x] Plot for shared clonotypes.
- [ ] Add `vis.heatmap2` http://sebastianraschka.com/Articles/heatmaps_in_r.html .
- [x] Add MiXCR 2.0 format

**2.3 version**
- [ ] Add a general function for gene usage analysis / comparison `repGeneAnalysis` (PCA, entropy, JS-div).
- [ ] Add the `repOverlapAnalysis` function.
- [ ] Add error correction subroutine based on in-frame parent search and check other error correction subroutines for errors.
- [ ] Fix other error correction and decontamination procedures.

**2.4 version**
- [ ] Do something with `find.clonotypes` to make it simpler and cleaner.
- [ ] Optimise `shared.repertoire`.
- [ ] Add to `shared.repertoire` an option to skip some pairs of input data frames.

**future**
- [ ] Add a data structure for efficient representation of repertoires. (???)
  - [ ] Implement gene segments as factors.
  - [ ] Fast search for mutated neighbors between repertoires represented as such data structures.
  - [ ] Fast grep.
  - [ ] Memory efficient.
    - [ ] Implement nucleotide sequences as bit sequences with two-bit per bp (~ .5 memory consumption).
- [ ] Optimise other functions like `morisita.index` for use them with lists with data frames and / or rewrite them on C++ and / or write their parallel versions. [parallel](http://rcppcore.github.io/RcppParallel/)
## Vignette

**2.3 version**
- [ ] `vis.shared.clonotypes` manual.
- [ ] Add kmers examples and functions' descriptions.
- [ ] Add rarefaction analysis examples and functions' descriptions.
- [ ] Add description and examples for data filtering and decontamination.
- [ ] Add cool plots for mutation networks.
- [ ] Add `repGeneAnalysis` manual.
- [ ] Add `repOverlapAnalysis` manual.

**2.4 version**
- [ ] Check examples for `find.clonotypes` and make them cleaner (explain NAs in the output and / or add new examples).
## Other

**2.2.2 version**
- [ ] Add TCR and Ig gene segment alphabets (for all possible chains) and tables for human.
- [ ] Add TCR and Ig gene alleles alphabets (for all possible chains) and tables for human.
- [ ] Add TCR and Ig subgroups alphabets (for all possible chains) and tables for human.
- [x] Add TRAV / TRAJ data for mouse.

**2.3 version**
- [ ] Add TCR and Ig gene segment alphabets and tables for other than human species (from [here](http://www.imgt.org/IMGTrepertoire/LocusGenes/#F))
  - [ ] Mouse

**future**
- [ ] Add data for time points analysis (e.g., vaccination).
- [ ] Add a pipeline .Rmd file for time points analysis.
- [ ] Add tables with known antigenic clones and peptides:
  - [ ] Influenza
  - [ ] CMV
  - [ ] EBV
